# Generated by Django 4.1.2 on 2022-10-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Paymentapp", "0002_remove_coffee_razorpay_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="email",
            field=models.EmailField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coffee",
            name="mobile",
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
