# Generated by Django 4.1.2 on 2022-10-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Paymentapp", "0004_alter_coffee_email_alter_coffee_mobile"),
    ]

    operations = [
        migrations.RemoveField(model_name="coffee", name="email",),
        migrations.RemoveField(model_name="coffee", name="mobile",),
    ]
